config/routes.rb
SpictureWeb::Application.routes.draw do
  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"
  resources :identities
  resources :users

  resources :pictures do
    collection do
      post :upload
    end
  end

  resources :groups do
    collection do
      get :add_contact
      post :insert_contact
      post :remove_contact
    end
  end

  resources :albums do
    collection do
      get :add_picture
      get :remove_picture
      post :insert_picture
      post :drop_picture
      post :share_album
    end   

    member do
      get  :public_view
      post :share_with_contact
    end
  end

  resources :contacts
  
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :description, :user_id
  belongs_to :user

  has_many :c2gs
  has_many :contacts, :through => :c2gs, :uniq => true

  has_many :group_albumizations
  has_many :albums, :through => :group_albumizations, :uniq => true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new(:user_id => current_user.id)
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      flash[:notice] = "Successfully created Group."
      redirect_to current_user
    else
      render :action => 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      flash[:notice] = "Successfully updated group."
      redirect_to current_user
    else
      render :action => 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = "Successfully destroyed group."
    redirect_to current_user
  end

  def show
    @group = Group.find(params[:id])
  end

  def add_contact
    @c2g = C2g.new(:group_id => params[:group_id])
  end

  def insert_contact
    @group = current_user.groups.find(params[:c2g][:group_id])
    @c2g = C2g.new(params[:c2g])
    if @c2g.save
      flash[:notice] = "Successfully Added Contact."
      redirect_to @group
    else
      flash[:error] = "Could not add Contact to group!"
      redirect_to @group
    end
  end

  def remove_contact
    @group = current_user.groups.find(params[:contact_removal][:group_id])
    @c2g = @group.c2gs.find_by_contact_id(params[:contact_removal][:contact_id])

    if @c2g.destroy
      flash[:notice] = "Successfully removed Contact."
      redirect_to @group
    else
      flash[:error] = "Could not remove Contact from group!"
      redirect_to @group
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/add_contact.html.erb
<h3>
  <br/>
  <br/>
  Add Contact
</h3>

<div>
  <%= form_for @c2g, :url => insert_contact_groups_path do |f| %>
    <%= f.hidden_field :group_id %>
    <%= f.select(:contact_id, current_user.contacts.all.reject {|c| 
                                                        c.groups.collect(&:id).include?(params[:group_id].to_i)
                                                       }.collect{|c| 
                                                         ["#{c.name}: #{c.email}", c.id]
                                                       }, { :include_blank => true }
                ) 
    %>

    <%= f.submit("Add Contact") %>
  <% end %>
</div>

app/views/groups/new.html.erb
<%= form_for @group do |f| %>
  <%#= f.error_messages %>
  <%= f.hidden_field :user_id %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/groups/show.html.erb
<h3>
  <%= @group.name %>
</h3>

<div>
  <div>
    <%= form_for :c2g, :url => insert_contact_groups_path do |f| %>
      <%= f.hidden_field :group_id, :value => @group.id %>
      <%= f.select(:contact_id, current_user.contacts.all.reject {|c| 
                                                          c.groups.collect(&:id).include?(params[:group_id].to_i)
                                                         }.collect{|c| 
                                                           ["#{c.name}: #{c.email}", c.id]
                                                         }, { :include_blank => true }
                  ) 
      %>

      <%= f.submit("Add Contact") %>
    <% end %>
  </div>

<br/> 

  <div>
    <%= form_for :contact_removal, :url => remove_contact_groups_path do |f| %>
      <%= f.hidden_field :group_id, :value => params[:id] %>
      <p>
        <%= f.select(:contact_id,@group.contacts.collect{ |c|
                              ["#{c.name}: #{c.email}", c.id]
                             }, { :include_blank => true }
                    ) 
        %>
        <%= f.submit "Remove Contact" %>
      </p>
    <% end %>
  </div>
</div>

<br/>

<div>
  <%= form_for :album_mailer, :url => share_album_albums_path do |f| %>
    <%#= f.error_messages %>
    <%= f.hidden_field :group_id, :value => params[:id] %>
    <p>
      <%= f.select(:id, current_user.albums.collect{|a| [a.name, a.id]}, { :include_blank => true }) %>
      <%= f.submit "Share Album with Group" %>
    </p>
  <% end %>
</div>

<br/>

<h4>
  Contacts:
</h4>
<div id="group_contacts">
  <% @group.contacts.each do |c| %>
    <li>
      <div id="images_list">
        <%= link_to c.name, c %>
        <p>
          <% c.email %>
        </p>
      </div>
    </li>
    <br/>
  <% end %>
</div>