config/routes.rb
SpictureWeb::Application.routes.draw do
  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"
  resources :identities
  resources :users

  resources :pictures do
    collection do
      post :upload
    end
  end

  resources :groups do
    collection do
      get :add_contact
      post :insert_contact
      post :remove_contact
    end
  end

  resources :albums do
    collection do
      get :add_picture
      get :remove_picture
      post :insert_picture
      post :drop_picture
      post :share_album
    end   

    member do
      get  :public_view
      post :share_with_contact
    end
  end

  resources :contacts
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :description, :user_id
  has_many :groups
  has_many :pictures
  has_many :contacts
  has_many :albums

  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h3>
Test
</h3>

app/views/users/show.html.erb
<div id="user_info">
  <h3>User : <%= current_user.name if current_user %> </h3>   
</div>

<div>
  <%= link_to "New Picture", new_picture_path %>
  <%= link_to "New Contact", new_contact_path %>
<div>
  <br/>
<div>
  <%= link_to "View Pictures", pictures_path %>
  <%= link_to "View Contacts", contacts_path %>
<div>

</br>
</br>
<div>
    <div id="groups_list">
      <%= button_to "Create Album", new_album_path, :method => :get %>

      <ul id="user_albums" style="list-style-type: none" >
        <% current_user.albums.each do |a| %>
          <li class="interface_box" style="background-color: #FFFFFF; width:200px; height:35px"><%= link_to a.name, a %></li>
          <br/>
        <% end %>
      </ul>
    </div> 
    
    <div id="albums_list" >
      <%= button_to "Create Group", new_group_path, :method => :get %>
      <ul id="user_albums"groups style="list-style-type: none" >
        <% current_user.groups.each do |g| %>
          <li class="interface_box" style="background-color: #FFFFFF; width:200px; height:35px"><%= link_to g.name, g %></li>
          <br/>
        <% end %>
      </ul>
    </div>
</div>

<div style="color:#fff">_</div>