config/routes.rb
SpictureWeb::Application.routes.draw do
  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"
  resources :identities
  resources :users

  resources :pictures do
    collection do
      post :upload
    end
  end

  resources :groups do
    collection do
      get :add_contact
      post :insert_contact
      post :remove_contact
    end
  end

  resources :albums do
    collection do
      get :add_picture
      get :remove_picture
      post :insert_picture
      post :drop_picture
      post :share_album
    end   

    member do
      get  :public_view
      post :share_with_contact
    end
  end

  resources :contacts
  
  

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :description, :user_id
  belongs_to :user

  has_many :p2as
  has_many :pictures, :through => :p2as, :uniq => true

  has_many :group_albumizations
  has_many :groups, :through => :group_albumizations

  def public_url
     "http://ec2-23-23-233-62.compute-1.amazonaws.com/albums/" + self.id.to_s + "/public_view"
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new(:user_id => current_user.id)
  end

  def create
    @album = Album.new(params[:album])
    if @album.save
      flash[:notice] = "Successfully created Album."
      redirect_to current_user
    else
      render :action => 'new'
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(params[:album])
      flash[:notice] = "Successfully updated album."
      redirect_to current_user
    else
      render :action => 'edit'
    end
  end

  def destroy
    @album = current_user.albums.find(params[:id])
    @album.destroy
    flash[:notice] = "Successfully destroyed album."
    redirect_to current_user
  end

  def show
    @album = current_user.albums.find(params[:id])
  end

  def add_picture
    @p2a = P2a.new(:album_id => params[:album_id])
  end

  def remove_picture
    @album = current_user.albums.find(params[:album_id])
  end

  def share_album
    @album = current_user.albums.find(params[:album_mailer][:id])
    
    @group = current_user.groups.find(params[:album_mailer][:group_id])
    
    @group.contacts.each do |c|
      #mail the album to each contact in the group
      AlbumMailer.album_shared(c, @album).deliver
    end
  
    flash[:notice] = "Email Sent!"

    redirect_to @album
  end

  def share_with_contact
    @album = current_user.albums.find(params[:album_mailer][:id])
    @contact = current_user.contacts.find(params[:album_mailer][:contact_id])
    AlbumMailer.album_shared(@contact, @album).deliver

    flash[:notice] = "Email Sent!"

    redirect_to @album
  end

  def insert_picture
    @p2a = P2a.new(:album_id => params[:album_id], :picture_id => params[:picture_id])
    if @p2a.save
      flash[:notice] = "Successfully Added Picture."
      redirect_to @p2a.album
    else
      flash[:error] = "Could not add Picture to Album!"
      redirect_to @p2a.album
    end
  end

  def drop_picture
    @album = current_user.albums.find(params[:album_id])
    @p2a = @album.p2as.find_by_picture_id(params[:picture_id])

    if @p2a.destroy
      flash[:notice] = "Successfully Removed Picture."
      redirect_to @album
    else
      flash[:error] = "Could not remove Picture from Album!"
      redirect_to @album
    end
  end

  def public_view
    @album = Album.find(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/add_picture.html.erb
<h3>
  Add Picture
</h3>

<div>
  <ul>
    <% current_user.pictures.all.reject {|p| p.albums.collect(&:id).include?(params[:album_id].to_i)}.each do |p| %>
       <li>
          <%= link_to image_tag(p.image_url, :width => 72, :height => 72), insert_picture_albums_path(
                                                                            :album_id => params[:album_id], 
                                                                            :picture_id => p.id), 
                                                                            :method => :post 
          %>
       </li>
    <% end %>
  </ul>
</div>

app/views/albums/new.html.erb
<h3>
Create A New Album
</h3>

<%= form_for @album do |f| %>
  <%#= f.error_messages %>
  <%= f.hidden_field :user_id %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/albums/public_view.html.erb
<% row_length = 10 %>
<h3>
  Album: <%= @album.name %>
</h3>

<br/>

<table id="user_images">
  <% @album.pictures.each_with_index do |p, ndx| %>
    <% if ((ndx%row_length) == 0) && (ndx!=0) %>
      <tr>
    <% end %>
      <td>
        <%= link_to(
          image_tag(p.image_url, :width => 72, :height => 72),
          p.image_url
        ) if p.image?
        %>
      </td>
    <% if ((ndx%row_length) == 0) && (ndx!=0) %>
      </tr>
    <% end %>  
  <% end %>
</table>

app/views/albums/remove_picture.html.erb
<h3>
  Remove Picture
</h3>

<div>
  <ul>
    <% @album.pictures.all.each do |p| %>
       <li>
          <%= link_to image_tag(p.image_url, :width => 72, :height => 72), drop_picture_albums_path(
                                                                              :album_id => params[:album_id], 
                                                                              :picture_id => p.id), 
                                                                              :method => :post 
          %>
       </li>
    <% end %>
  </ul>
</div>

app/views/albums/show.html.erb
<% row_length = 10 %>
<h3>
 Album: <%= @album.name %>
</h3>

<div>
  <%= link_to "Add Picture", add_picture_albums_path(:album_id => @album.id) %>
  <br/>
  <%= link_to "Remove Picture", remove_picture_albums_path(:album_id => @album.id) %>
  <br/>
  <%= link_to "View Public Album Page", public_view_album_path(:album_id => @album.id) %>
</div>

<br/>

<div>
  <%= form_for :album_mailer, :url => share_album_albums_path do |f| %>
    <%#= f.error_messages %>
    <%= f.hidden_field :id, :value => params[:id] %>
    <p>
      <%= f.select(:group_id, current_user.groups.collect{|g| [g.name, g.id]}) %>
      <%= f.submit "Share With Group" %>
    </p>

  <% end %>
</div>

<div>
  <%= form_for :album_mailer, :url => share_with_contact_album_path do |f| %>
    <%#= f.error_messages %>
    <%= f.hidden_field :id, :value => params[:id] %>
    <p>
      <%= f.select(:contact_id, current_user.contacts.collect{|c| ["#{c.name} - #{c.email}", c.id]}, { :include_blank => true }) %>
      <%= f.submit "Share Album with Contact" %>
    </p>
  <% end %>
</div>

<br/>

<h4>
  Pictures:
</h4>

<table id="user_images">
  <% @album.pictures.each_with_index do |p, ndx| %>
    <% if ((ndx%row_length) == 0) && (ndx!=0) %>
      <tr>
    <% end %>
      <td>
        <%= link_to(
          image_tag(p.image_url, :width => 72, :height => 72),
          p.image_url
        ) if p.image?
        %>
      </td>
    <% if ((ndx%row_length) == 0) && (ndx!=0) %>
      </tr>
    <% end %>  
  <% end %>
</table>